---
- name: Weekly system reboots and enforcing security guidelines and enforce & revert configuration if changed on localhost
  hosts: 172.31.38.102
  become: yes
  gather_facts: yes

  tasks:
    - name: Schedule Weekly System Reboot
    # Task to schedule a weekly system rebot using a cron job
      cron: 
        name: "Weekly System Reboot"
        minute: "0"
        hour: "4" # Adjust the desired time for reboot(4 AM for this example)
        weekday: "6" #6 is for Saturday, adjust as needed
        user: root
        job: "/sbin/reboot"
      register: cron_result
      when: ansible_os_family == 'Amazon linux'

    - name: Ensure the Weekly Reboot is applied
      command: crontab -u root -l 
      register: current_cron
      when: ansible_os_family == 'Amazon linux'

    - name: Display Current Cron Job
      debug:
        var: current_cron.stdout_lines
    when: ansible_os_family == 'Amazon linux'

    - name: Reboot if Scheduled
      command: "/sbin/reboot"
      when: "'Reboot weekly' in current_cron.stdout"
      async: 0
      poll: 0
      ignore_errors: true

    - name: Ensure Reboot
      wait_for_connection:
        timeout: 300
      when: "'Reboot Weekly' in current_cron.stdout"  